CURSO_C#_WEB/Models/APIRequest.cs
using static CURSOC__UTILITY.DS;

namespace CURSO_C__WEB.Models
{
    public class APIRequest
    {
        public APITipo APITipo { get; set; } = APITipo.GET;

        public string Url { get; set; }

        public object Data { get; set; }
    }
}

CURSO_C#_WEB/Models/APIRespose.cs
using System.Net;

namespace CURSO_C__WEB.Models
{
    public class APIRespose
    {
        public HttpStatusCode statusCode { get; set; }

        public bool IsSuccessful { get; set; } = true;

        public List<string> ErrorMessages { get; set; }

        public object? Result { get; set; }
    }
}

CURSO_C#_WEB/Models/DTO/ProvinciaDTO.cs
using System.ComponentModel.DataAnnotations;

namespace CURSO_C__WEB.Models.DTO
{
    public class ProvinciaDTO
    {
        [Required]
        [MaxLength(20)]
        public string? nomprovincia { get; set; }
    }
}

CURSO_C#_WEB/Models/ErrorViewModel.cs
namespace CURSO_C__WEB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CURSO_C#_WEB/Controllers/HomeController.cs
using CURSO_C__WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CURSO_C__WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CURSO_C#_WEB/Controllers/ProvinciaWController.cs
using CURSO_C__WEB.Models;
using CURSO_C__WEB.Models.DTO;
using CURSO_C__WEB.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CURSO_C__WEB.Controllers
{
    public class ProvinciaWController : Controller
    {
        private readonly IProvinciaService _provinciaService;

        public ProvinciaWController(IProvinciaService provinciaService)
        {
            _provinciaService = provinciaService;
        }

        public async Task<IActionResult> IndexProvincia()
        {
            List<ProvinciaDTO> provinciaList = new();
            var response = await _provinciaService.ObteinAllP<APIRespose>();
            if (response != null && response.IsSuccessful)
            {
                provinciaList = JsonConvert.DeserializeObject<List<ProvinciaDTO>>(Convert.ToString(response.Result));
            }
            return View(provinciaList);
        }

        //NO definido es un metodo Get, llama vista
        public async Task<IActionResult> CreateProvincia()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]//SEGURIDAD PARA ENVIO DE DATOS
        public async Task<IActionResult> CreateProvincia(ProvinciaDTO provinciaDTO)
        {
            if (ModelState.IsValid)
            {
                var response = await _provinciaService.CreateP<APIRespose>(provinciaDTO);
                if (response != null && response.IsSuccessful)
                {
                    return RedirectToAction(nameof(IndexProvincia));
                }
            }
            return View(provinciaDTO);
        }
    }
}

CURSO_C#_WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CURSO_C#_WEB/Views/ProvinciaW/CreateProvincia.cshtml
@model CURSO_C__WEB.Models.DTO.ProvinciaDTO
@{
    ViewData["Title"] = "CreateProvincia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateProvincia</h1>
<form method="post" asp-action="CreateProvincia">
    <div class="container boder p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <h2 class="text-info"> Create New Provincia</h2>
        </div>
        <div class="row mt-2">
            <div class="col-md-6">
                <label class="form-label">Name Provincia </label>
                <input asp-for="nomprovincia" class="form-control" />
                <span asp-validation-for="nomprovincia" class="text-danger"></span>
            </div>
        </div>

        <div class="d-grid gap-2 d-md-block mt-2">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-controller="Provincia" asp-action="IndexProvincia" class="btn btn-success">Return Back </a>
        </div>
    </div>
</form>

CURSO_C#_WEB/Views/ProvinciaW/IndexProvincia.cshtml
@model IEnumerable<CURSO_C__WEB.Models.DTO.ProvinciaDTO>
@{
    ViewData["Title"] = "IndexProvincia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="Container p-4" border>
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Lista de provincias</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="ProvinciaW" asp-action="CreateProvincia" class="btn btn-outline-primary"><i class="bi bi-plus-circle"></i> Crear Provincia</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>NOMBRE</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.nomprovincia</td>
                    <td>
                        <a asp-controller="ProvinciaW" asp-action="EditProvinciaC" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="ProvinciaW" asp-action="DeleteProvinciaC" class="btn btn-outline-primary"><i class="bi bi-x-square"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CURSO_C#_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CURSO_C__WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CURSO_C__WEB.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CURSO_C__WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProvinciaW" asp-action="IndexProvincia">Provincias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CURSO_C__WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>